### ISSUE TITLE
Problem on Galaxy S6 Edge

### ISSUE THREAD

**Issue by edegut** [halkar/Tesseract.Xamarin#21] opened 2015-11-02 10:31 UTC
Hi, 

I've got a crash when I initialise my TesseractAPI :
 dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libpngt.so"

Any idea?

**Comment by halkar** [comment] 2015-11-02 10:40
Which version do you use? It should be fixed in one of the lady ones.

Sent from Outlook




On Mon, Nov 2, 2015 at 2:31 AM -0800, "edegut" <notifications@github.com> wrote:












Hi, 



I've got a crash when I initialise my TesseractAPI :

 dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libpngt.so"



Any idea?

**Comment by edegut** [comment] 2015-11-02 10:50
I use version 0.2.9

**Comment by halkar** [comment] 2015-11-02 20:36
Which Android version are you running?

**Comment by edegut** [comment] 2015-11-03 10:51
Excuse me, there was no problem in fact. I made a mistake in my project
configuration.

2015-11-02 21:36 GMT+01:00 Artur Shamsutdinov <notifications@github.com>:

**Comment by halkar** [comment] 2015-11-03 11:03
No worries. Could you please give some details on that mistake?

**Closed** 2015-11-03 22:15 UTC

**Comment by sabrinaj** [comment] 2015-11-10 14:14
Hello,

I currently have the same problem, would it be possible to have some details ?

Thanks !

**Comment by halkar** [comment] 2015-11-18 12:20
@sabrinaj I managed to reproduce this issue only once and only in Visual Studio. Looks like it can be caused by the build configuration. After disabling/enabling fast deployment and shared runtime options problem has gone.

**Comment by halkar** [comment] 2015-11-18 12:24
@sabrinaj also please check which architectures you are targeting.

**Comment by halkar** [comment] 2015-11-23 10:05
@sabrinaj I managed to reproduce this issue but after updating my dev environment to VS2015 and last version of Xamarin 4 I can't reproduce this issue anymore.
